stages:
    - build
    - test

image: izytechab/nette:latest

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
  # Install PHP extensions
  - docker-php-ext-install pdo_pgsql curl json intl gd xml zip bz2 opcache
  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

build:
  stage: build
  script:
    - echo "build"

test:
  stage: test
  script:
    - echo "test"