stages:
  - build
  - test

image: izytech/nette

cache:
  paths:
    - vendor/

before_script:
  - echo "before"

test:
  stage: test
  script:
    - echo "test"
build:
  stage: build
    - echo "build"
