stages:
    - build
    - test

image: php:latest

cache:
  paths:
    - vendor/

before_script:
  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

build:
  stage: build
  script:
    - echo "build"

test:
  stage: test
  script:
    - echo "test"